### ISSUE TITLE
Installation on Lazarus 2.0.10

### ISSUE THREAD

**Issue by JReally** [digao-dalpiaz/DzHTMLText#14]
Previous installation on Lazarus 2.0.8 was successful but Lazarus 2.0.10 gives the following error on compile
Compile package LazDzHTMLText 0.0: Exit code 1, Errors: 2
DzHTMLText.pas(31,41) Error: class type expected, but got "TObjectList$1.T"
DzHTMLText.pas(31,43) Error: class type expected, but got "<erroneous type>"

**Comment by digao-dalpiaz** [comment]
Hey Jon,

I have already installed Lazarus 2.0.10 and It's really a bug.

The generics declaration has changed. I'll fix it.

**Comment by digao-dalpiaz** [comment]
Done.

Thank you for enjoying the component.

Please let me know if there is anything else to adjust / improve.

**Comment by digao-dalpiaz** [comment]
About the antivirus accusing false positive in the zip file, it is probably because there is the program "**CompInstall.exe**", which is a utility that I created to install the components for **Delphi**. As this utility does not have a _digital signature_, it is possible for antivirus to recognize it as a suspicious file.
