### ISSUE TITLE
Numbers cut in display

### ISSUE THREAD

**Issue by Chandlr** [digao-dalpiaz/DzHTMLText#44]
Sorry again for disturbing but i found a display bug not sure how it happends.
I'll attach a photo of the cut-numbers

![NumbersCut](https://user-images.githubusercontent.com/1159592/111863619-faa44c00-895c-11eb-81ac-089884fce899.png)

**Comment by digao-dalpiaz** [comment]
Is this in FMX framework?

**Comment by Chandlr** [comment]
yes FMX 10.4.2 version Prof :)

**Comment by digao-dalpiaz** [comment]
I guess I know whats going on.

In FMX environment, the fonts length in pixels are provided in floating point value, instead of integer value provided by VCL one.
In this case, the character size must be occupying a larger space than expected.

But I need to confirm that.
As soon as possible I'll check this problem.

**Comment by digao-dalpiaz** [comment]
Hello @Chandlr ,

Please, download this branch: https://github.com/digao-dalpiaz/DzHTMLText/tree/fmx-pixels-single-support
And do a test to see if the problem will still occur.

Thanks.

**Comment by Chandlr** [comment]
It seems to be fixed now, that was quick 👍 
![Bug_Fixed](https://user-images.githubusercontent.com/1159592/111915912-cc1b9380-8a78-11eb-83b0-e97dddce4bfd.png)

**Comment by digao-dalpiaz** [comment]
New version 3.3 available with this fix.
