### ISSUE TITLE
Updating component with Installer

### ISSUE THREAD

**Issue by Chandlr** [digao-dalpiaz/DzHTMLText#46]
Hi this might be wrong section but i tried to update with CompInstall.exe and i got this:
Might be because of no zip file found, otherwise all looks good :)

> Checking for component update...
> New version "3.3" available.
> Downloading new version...
> Extracting new Component Install app...
> ERROR: Component Installer not found in zip file

**Comment by digao-dalpiaz** [comment]
Hello @Chandlr ,

Of course, I have removed Component Installer from components source, and I forgot to change this behavior in Component Installer engine.

Thank you for letting me know.
I'll fix this in the Component Installer.

**Comment by digao-dalpiaz** [comment]
Fixed.
You can download the new Component Installer version:
https://github.com/digao-dalpiaz/CompInstall

**Comment by Chandlr** [comment]
It works :)

**Comment by Chandlr** [comment]
"C:\Users\Public\Documents\Embarcadero\Studio\21.0\Bpl" bpl get copied there but source for reading references ? :) (Installer)
Delphi compiles fine during compile and install looks good.
But what i am wondering about is where is .pas supposed to be ? :)

i get:

> [MSBuild Error] The <ProjectExtensions> element occurs more than once.
> [EvaluateProperties Error] The <ProjectExtensions> element occurs more than once.

And Delphi asks me where source of pas files are located
might be a bug ? - .dpk files might be good to have there too.. dunno ?

**Comment by digao-dalpiaz** [comment]
Hello @Chandlr ,

It is not indicated that the component sources are made available after compilation, for performance reasons. Otherwise, each compilation of any application that uses the component, will compile the component again, in addition to disturbing the debug.

In this case, it is correct that the .pas files are not visible by the application.

Are these errors you are getting, occurring in CompInstall?
