### ISSUE TITLE
take changes from forked project?

### ISSUE THREAD

**Issue by Alexey-T** [digao-dalpiaz/DzHTMLText#50]
https://github.com/jackdp/DzHTMLText2
If you can merge its changes, it will be good, no?

**Comment by digao-dalpiaz** [comment]
Hello @Alexey-T ,

I know, this fork had a lot of changes some time ago.
In fact, jackdp made the initial Lazarus support code for my component. :)

However, unfortunately my component has undergone sudden changes since then, such as the inclusion of FMX support, support for Spoilers, Floating Panels, Edge Spacing, Theme Support, and many other improvements.

As you can see, the component codes are currently quite different, not allowing them to be merged:

> This branch is 10 commits ahead, 231 commits behind digao-dalpiaz:master.

**Anyway, if there is any improvement you need, please indicate here that I will do my best to make it available in the component.**

Thanks.
