### ISSUE TITLE
Invalid link object

### ISSUE THREAD

**Issue by NORECS** [digao-dalpiaz/DzHTMLText#59]
I'm using DzHTMLText for showing tabulated data as a table with bunch of links.

All links are done with same routine, and many of them work, but clicking some of them cause access violation, and some of them cause exception 'Invalid link object'.

Don't know if it is relevant, but there are many links with same 'href' and/or same 'text'.

**Comment by digao-dalpiaz** [comment]
Hello @NORECS,

Can you send us the HTML code?

**Comment by NORECS** [comment]
Some more info:

I am iterating a loop once per second where the whole text property is rewritten over and over again. I think the expired link objects are not nilled properly or something similar.

Did some testing, clicking 'same' link (well, the text property has been reset meanwhile, but the text to create the link is same) mostly clicking works, sometimes I get invalid link object exception.

I tried making the urls and link names unique (unique even among different cycles, with #integer suffix), didn't help.

HTML:

<T:5><B>Age</B><T:110><B>Block</B><T:210><B>Hash</B><T:280><B>Transaction</B><T:850><B>Token</B><T:1000><B>Amount</B><T:1250><B>BNB worth</B>
<T:5>02:38:01<T:110><A:www.bscscan.com/block/12246808#240>12246808#241</A><T:210><A:www.bscscan.com/tx/0x3d4399171568fb09e6fb3445c1fb78c67908328f708ebff2242a88b1f9ac832d#242>Hash#243</A><T:280>0xdbe831064ae9b8644de09f270eef3f0076ce9def:Receive<T:850><A:www.bscscan.com/token/0x2859e4544c4bb03966803b044a93563bd2d0dd4d#244>SHIB#245</A><T:1000>1809.46105957031<T:1250>0

**Comment by digao-dalpiaz** [comment]
Hello @NORECS ,

Thanks for the info. I think I know what is going on:

1. You fill Text property with some HTML code, containing links.
2. You put the mouse cursor over the link.
3. The Timer is triggered, changing all text, rewriting all links (there is an internal list of links, the list is cleared every time you change the text).
4. Because the mouse is over some link when you change the text, **although the list of links is rebuilt, however the internal object that contains the selected link is still the same because the mouse hasn't moved.**
5. When you click the same selected link, an access violation occurs.

There is an internal _FSelectedLink_ property that controls this behavior.

**I think clearing this property when text changes will fix this problem.**

Today I can't confirm this, but as soon as possible I will confirm and fix this problem.

Let's keep in touch.

**Comment by NORECS** [comment]
I can confirm that FSelectedLink := nil; in the SetText procedure works.

**Comment by digao-dalpiaz** [comment]
Fixed!
