### ISSUE TITLE
Possibly virus?! - CompInstall.exe

### ISSUE THREAD

**Issue by avmaksimov** [digao-dalpiaz/DzHTMLText#64]
Please, solve this problem: https://www.virustotal.com/gui/file/54237cbfe6cfc2e88090f12731e15c8c1af1fb19b465654ce6ab6d3533f9533e

**Comment by digao-dalpiaz** [comment]
Hello, what file are you submitting to VirusTotal ?

**Comment by avmaksimov** [comment]
> Hello, what file are you submitting to VirusTotal ?

CompInstall.exe from https://github.com/digao-dalpiaz/CompInstall/releases/tag/v2.5 . Also I see that threat was found after Compile dproj file in Delphi 10.4.2.

**Comment by digao-dalpiaz** [comment]
Hello, 

This is because the CompInstall software contains code to run and monitor external processes to call MSBUILD execution, and also contains use of HTTP request for update checking on GitHub.

In this way, the antivirus ends up accusing as a **false positive**.

The solution to this problem is to submit the EXE for analysis by antivirus companies.
Usually, after a few days of submitting the file, it stops being accused as a virus.

**Comment by avmaksimov** [comment]
I send it to Bitdefender and Kaspersky.

**Comment by digao-dalpiaz** [comment]
Great, thanks!
