### ISSUE TITLE
Any workaround for transparent DzHTMLText under VCL? 

### ISSUE THREAD

**Issue by PlanetIrata** [digao-dalpiaz/DzHTMLText#75]
Question in the title, I really need to have transparent DzHTMLText, is there a workaround for this ? Setting `ParentColor` do not work with default Windows theme...

If it's not possible do you now how to retrieve the color of a `TTabSheet` in Delphi in order to apply it at runtime to all my `DzHTMLText` ?

Thanks for any idea/workaround you may post

**Comment by digao-dalpiaz** [comment]
Hello,

There is a problem when getting background color:

![image](https://github.com/digao-dalpiaz/DzHTMLText/assets/46692097/097451e0-7636-4400-8bed-c396e96610d3)

I'm working on a fix for this

**Comment by WeberAndre** [comment]
Hello,
I solved it that way - not sure if this is right - I let paint the background  of your control from the parent control useing the a function simlar to Vcl.Controls.PerformEraseBackground(Self, C.Handle);  so the TBitmap (B) is initialized with the background of the parent control - and you can paint on this like before. (And it looks transparent?)

procedure PerformEraseBackgroundBitmap(Control: TGraphicControl;  background: TBitmap);
var
   LastOrigin: TPoint;
   DC: THandle;
begin
  background.Canvas.Lock;
  DC := background.Canvas.Handle;
  GetWindowOrgEx(DC, LastOrigin);
  SetWindowOrgEx(DC, Control.Left, Control.Top, nil);
  Control.Parent.Perform(WM_ERASEBKGND, DC, DC);
  SetWindowOrgEx(DC, LastOrigin.X, LastOrigin.Y, nil);
  background.Canvas.UnLock;
end;

**Comment by digao-dalpiaz** [comment]
This approach is very interesting. I'm checking out some possibilities...

**Comment by digao-dalpiaz** [comment]
Hello @WeberAndre, I tried running your code here but it didn't work.

Is there any other part of the code that you used to make it work?

**Comment by WeberAndre** [comment]
I have created a pull request with another idea to make it transparent. The Original Idea was not the right way - and only painted the ParentBackground into the Bitmap. The new way is to use [csOpaque] for transparency like TCustomLabel does this. But instead of Painting directly on the TCanvas of the control - I BitBlt the allready painted stuff into the TBitmap before painting on this.

**Comment by digao-dalpiaz** [comment]
Hello.

I reviewed your pull request and ran some tests.

It will not be possible to apply transparency to the component when using the VCL framework, as the Canvas painting method causes flickering when using Links, for example in text. Furthermore, this implementation of copying the background as an image (SCRCOPY) consumes a lot of resources and causes an overload when using Double Buffered.

Still on transparency, at the beginning of the component's development it allowed transparency, but it was discontinued precisely because of the problems mentioned above.

I'm studying the Delphi source codes to obtain the corresponding color of the theme when using it within a TabSheet. In this case it will not be a transparency, but rather a background color applied.

**I'm currently working on a complete refactoring of the component's engine, which is currently being tested. When the next version (5.0) is released, I will check this background color issue.**
I plan to do that soon.

**Comment by digao-dalpiaz** [comment]
I was thinking about this transparency property here and I implemented this property in this new version (5.0), but it works in another way: 

When transparent TRUE, the Bitmap cache is not used to draw the content, and this way transparency occurs natively.

Remembering: if this combination is used with links, for example, it will cause flickering, but when used without links it will work normally.
This way it is also compatible with Double Buffered.

**Comment by digao-dalpiaz** [comment]
![image](https://github.com/digao-dalpiaz/DzHTMLText/assets/46692097/2d637127-8ab4-48aa-96e3-467cf4f49643)

**Comment by digao-dalpiaz** [comment]
Testing version available at:
https://github.com/digao-dalpiaz/DzHTMLText/tree/engine-refact

**Comment by digao-dalpiaz** [comment]
Done!
