### ISSUE TITLE
A bug while using SPACE to split words

### ISSUE THREAD

**Issue by GitCnSH-DSLIN** [digao-dalpiaz/DzHTMLText#8]
It will be wrong if some none-space separated language used, such as Chinese or Japanese. For example:
    Lb.Width := 400;
    Lb.Height = 100;
    Lb.Text := 'This is an important text很好很好很好很好很好很好很好很好很好很好很好！</b>';
    AutoWidth := False;

**Comment by GitCnSH-DSLIN** [comment]
I‘v removed the split words by space, and changed it from a component to a pure object. Please reference to my brunch, thanks!

**Comment by digao-dalpiaz** [comment]
Hey @GitCnSH-DSLIN,

Yeah, this is a little complicated, because in English, for example, we need to split words by space. Otherwise in Chinese/Japanese, we need break lines by char.

So, we can add a published property to set this. But, assuming that a Chinese Developer coding apps and using DzHTMLText, so all components need to set this property.

In the other hand, we can detect local settings and set this automatically. But, assuming that the Developer will code and international app to work with multiple languages, so we need to adjust this manually.

So, I'm still thinking about this issue.
If you have some suggestion, please tell me.
Thanks.

**Comment by digao-dalpiaz** [comment]
Hello @GitCnSH-DSLIN,

After a long study of Chinese, Japanese and Korean characters, and studying the Unicode codes for each of them, I created a branch to make the adjustment in the component so that it is flexible with the characters, detecting according to the code established in the Unicode standards.

In this way, it is now possible to mix English characters with Chinese characters, for example, that the words and lines break will occur in an expected way.

Please, if possible, do a test with the branch referenced in this issue, and return me with your opinion.

Thanks.

**Comment by GitCnSH-DSLIN** [comment]
I've tested it with some cases, it's OK! You are so GREAT!!
